--- 

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 
    - name: Update
      apt:
        update_cache: yes
        upgrade: yes

- hosts: all
  remote_user: root
  roles:
    - role: ansible-role-mysql
    - role: ansible-role-pip
    - role: ansible-role-readthedocs
