--- 

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 
    - name: Update
      apt:
        update_cache: yes
        upgrade: yes

- hosts: all
  remote_user: root
  roles:
    - role: ansible-role-mysql
    - role: ansible-role-nginx
    - role: ansible-role-pip
    - role: ansible-role-readthedocs

- hosts: all
  remote_user: root
  tasks:
    - name: Install nginx config
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx